# 这里是项目中所有需要配置地址的汇总, 需要修改哪个中间件的地址在此处修改即可.
mintcraft:
  mysql:
    # MySQL 的地址 + 数据库配置
    url: jdbc:mysql://127.0.0.1:13306/mintcraft
    # MySQL 的用户名
    username: root
    # MySQL 的密码
    password: MC123456
  redis:
    # Redis 的地址
    url: 127.0.0.1
    # Redis 的端口号
    port: 16379
    # Redis 的密码
    password: 'MC123456'
  nacos:
    server:
      # Nacos 的地址+端口号
      url: 127.0.0.1:8848
  dubbo:
    nacos:
      # nacos 上的给 dubbo 用的 namespace
      namespace: dubbo_server
      # nacos 上的给 dubbo 用的 group
      group: dubbo
  elasticsearch:
    # 是否使用 es
    enable: true
    # ElasticSearch 的地址 + 端口号
    url: 127.0.0.1:9200
    # ElasticSearch 的用户名
    username: elastic
    # ElasticSearch 的密码
    password: 123456