spring:
  application:
    name: mint-craft-inventory
  config:
    import: optional:classpath:base.yml, optional:classpath:rpc.yml, optional:classpath:cache.yml, optional:classpath:limiter.yml

server:
  port: 8087
