spring:
  application:
    name: mint-craft-notice
  config:
    import: optional:classpath:base.yml, optional:classpath:datasource.yml, optional:classpath:rpc.yml, optional:classpath:cache.yml
  profiles:
    active: dev

server:
  port: 8089
