spring:
  profiles:
    active: dev
  application:
    name: mint-craft-pay
  config:
    import: optional:classpath:base.yml, optional:classpath:datasource.yml, optional:classpath:rpc.yml, optional:classpath:cache.yml, optional:classpath:job.yml, optional:classpath:limiter.yml

server:
  port: 8088