spring:
  profiles:
    active: dev
  application:
    name: mint-craft-pay
  config:
    import: optional:classpath:base.yml, optional:classpath:datasource.yml, optional:classpath:rpc.yml, optional:classpath:cache.yml, optional:classpath:job.yml, optional:classpath:limiter.yml

seata:
  application-id: MintCraft
  tx-service-group: default_tx_group
  config:
    type: file
  registry:
    type: file
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091

server:
  port: 8088